### PR TITLE
Cleanup line endings

### LINKED ISSUE #242: Cleanup line endings
Can be done easily with this bash snippet:
```bash
find -type f |  # list all regular files
grep -E '\.(h|cpp|fsh|vsh|mm)$' |  # filter for text files
xargs -n 1 sed -i 's:\s*$::'  # for each file, trim trailing whitespace including the CR
```
(and the same for LICENSE)
Should result in diff stats like:
```
$ git diff --stat | tail
 source/Irrlicht/CZipReader.h                       |  444 +-
 source/Irrlicht/IAttribute.h                       |  126 +-
 source/Irrlicht/Irrlicht.cpp                       |  318 +-
 source/Irrlicht/KHR/khrplatform.h                  |  580 +-
 source/Irrlicht/S2DVertex.h                        |   52 +-
 source/Irrlicht/SB3DStructs.h                      |  134 +-
 source/Irrlicht/SoftwareDriver2_helper.h           |  602 +-
 source/Irrlicht/os.cpp                             |  742 +-
 source/Irrlicht/os.h                               |  186 +-
 302 files changed, 99197 insertions(+), 99197 deletions(-)
$ git diff --stat --ignore-space-at-eol | tail
$
```
which aren’t good for a PR but necessary

### PR DESCRIPTION
**Pull request by numberZero**
Fix #242.

Can be reproduced with the commands described in the commit message.
Can also be checked with `git diff --ignore-space-at-eol`.
`git blame -w` is also useful.

### CODE REVIEW

**Comment by numberZero** [comment]
@sfan5 This is the first part of the wholesale cleanup.

Other PRs are likely easiest to rebase across this as patches as it’s easy to trim trailing whitespace from a patch.

**Comment by nerzhul** [comment]
Thanks, merged, let's move forward on this topic

**Comment by sfan5** [comment]
> Other PRs are likely easiest to rebase across this as patches as it’s easy to trim trailing whitespace from a patch.

Is there a convenient alternative? For example if I wanted to cherry-pick from the upstream commits.

**Comment by numberZero** [comment]
> Is there a convenient alternative? For example if I wanted to cherry-pick from the upstream commits.

Dunno. If the upstream is still SVN maybe git-svn offers something. Otherwise, `git format-patch` & `git am` (and after merging into Minetest, `git apply --directory=lib/irrlichtmt`)

**Comment by sfan5** [comment]
Here's what I'm using for cherry-picking now:
```
pick ()
{
	local rev=$1
	shift
	git format-patch --stdout "$rev^..$rev" | dos2unix | git am --reject "$@"
}
```

**Comment by SmallJoker** [comment]
FYI: based on issue reported in https://github.com/minetest/minetest/pull/14003/files this PR seems to have reverted commit c40045a40acf.

Honestly I could not care less about this particular commit and would rather welcome the Minetest PR to stay closer to upstream Irrlicht.

**Comment by numberZero** [comment]
@SmallJoker `git show --ignore-space-at-eol 9954667`
Also `git show --stat 9954667` to make sure no non-text files were changed (the “filter for text files” step was there for a reason).

**Pull request merged**
