### PR TITLE
Static glTF mesh loading

### PR DESCRIPTION
**Pull request by JosiahWI**
Part of https://github.com/minetest/minetest/issues/9673

We use tinygltf for the parsing and Catch2 for the unit tests. The loader currently supports static meshes in glTF text format, but tinygltf will make it easy to support binary glTF files in a future version. Because we intend to support as much of the glTF feature set as we can in the future, we need to ensure forward compatibility, and that's the main thing I want feedback on.

Feature set:
  - meshes with multiple primitives
  - floating point and unsigned normalized texcoords
  
Features not supported yet (planned for separate PRs):
  - static bones
  - animations
  - materials
  - probably some other things

TODO:
- [x] Handle byteStride that may be present on vertex buffers.
- [x] Handle u8 and u16 texture coordinates.
- [x] Print warnings and errors to log; I have the change somewhere, just need to find it.
- [x] Consider whether tinygltf should be modified to use a lighterweight JSON library such as jsoncpp. (discussed on Discord; keeping nlohmann-json for now)
- [ ] Add copyright notices to the source and header file.
- [x] Unit test and merge the fix for the scaling done by @jordan4ibanez.
  
Thank you to GreenXenith and appgurueu for all their assistance, and especially to jordan4ibanez for adding a lot of improvements.

### CODE REVIEW

**Comment by rollerozxa** [comment]
> What’s the value of glTF over Obj and B3D?

An animated model format that isn't obsolete.

**Comment by JosiahWI** [comment]
glTF has better tooling support. One of the major issues with b3d is that we don't have a good exporter for Blender>=3.0. Blender and Blockbench both export to glTF.

**Comment by JosiahWI** [comment]
Discussed offline, and I'm hearing that my previous statement is no longer true.

**Comment by Montandalar** [comment]
While the latest version GreenXenith's exporter may have Blender >=3.0 supporter, that exporter codebase is still not really very nice to deal with. While I can't vouch for the glTF exporters of various programs yet because I don't regularly use Blender or Blockbench for another application, I would still think they are a fair bit better than b3d tools, and more likely to improve than the old b3d tools we have basically had to maintain ourselves.

**Comment by rubenwardy** [comment]
See https://github.com/minetest/minetest/issues/9673

**Comment by numberZero** [comment]
> See [minetest/minetest#9673](https://github.com/minetest/minetest/issues/9673)

Thanks. Apparently the alternatives to glTF are worse.

@nerzhul I remember you were against making Irrlicht a submodule. But, tinygltf is another story, it’s not like we’re going to commit into it ourselves—so what’s your opinion on putting it into a submodule?

**Comment by JosiahWI** [comment]
There are some issues with the build, but the code part has been rebased.

**Comment by jordan4ibanez** [comment]
A rebase huh? I'll shelf my other PR and call it something dramatic

**Comment by appgurueu** [comment]
Current work in progress:

1. https://github.com/JosiahWI/irrlicht/pull/11
2. https://github.com/appgurueu/irrlicht/pull/2
3. https://github.com/appgurueu/irrlicht/pull/3

**Comment by JosiahWI** [comment]
Replaced by minetest#14557.

**Pull request closed without merging**
