### PR TITLE
OpenGL3: new version&feature checks

### PR DESCRIPTION
**Pull request by numberZero**
1. Save OpenGL spec and version in the driver (`initVersion`)
2. Fill feature support information accordingly (`initFeatures`)
3. Restore support for DrawBuffers as MRT is now properly reported as supported.

Follow-ups:
* #194 (may be considered an alternative)
* #195 
* #196

Note: [ce29446](https://github.com/minetest/irrlicht/pull/193/commits/ce29446a42866781bae447ce815af3a7cfb5c09e) is reverted in #194 as it uses a different approach.

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]

**Comment by numberZero** [comment]
Also, what’s your reasoning for squash vs. rebase vs. merge?

**Comment by sfan5** [comment]
* merge: not enabled in github ui so inconvenient to do. If you have a reason to use it I can do it next time.
* squash: will be annoying for rebasing your other PRs. I assume you wouldn't want this.
* rebase: I think linear history is nice.

**Comment by numberZero** [comment]
> * merge: not enabled in github ui

Argh... the one who did that might not be evil, but the one who advised certainly is.

> * squash: will be annoying for rebasing your other PRs. I assume you wouldn't want this.

I see. But “rebase” didn’t help. To my knowledge, for Git they are essentially the same, creating new commits unrelated to those in the “merged” branch. Only actual merge (or fast-forward, when applicable) is something Git keeps track of.

Anyway, I rebased my other PRs.

**Comment by numberZero** [comment]
> * rebase: I think linear history is nice.

Did you try `git log --first-parent --oneline`?

**Comment by numberZero** [comment]
Note that I’m not saying that rebasing own PRs is hard for me. It’s just some unnecessary friction. But doing merges manually is not a solution: it would be more per-PR friction *for you* which is even worse as you handle more PRs in the same time.

**Pull request merged**
