### PR TITLE
feat(win32): Add basic IME supports for Windows

### PR DESCRIPTION
**Pull request by snowyu**
The IME can be used basically on Windows.

dependency PR: GH-138

+ add `_IRR_USE_WIN32_IME` compiler directive, defaults to true
+ add `CIrrWin32IME.cpp/.h` for Windows IME helper functions
  * have to export for minetest's guiChatConsole
  * Maybe need to refact an abstract CGUIEditable class

Note: Sometime, some IMEs can not get char from `WM_IME_CHAR` message, so I have to use WM_IME_COMPOSITION to get it.

Anyway, It's worked basically.

### CODE REVIEW

**Comment by rubenwardy** [comment]
We're looking to move to SDL and strip out most of Irrlicht's event handling code. It's probably not worth doing this work just for it to be thrown away

**Comment by sfan5** [comment]
Note that it should not be necessary to add a special API for use by the GUI code.

Here's an example: 3ef59028155ba4cab0f734aecb6bdfc2aa90cbf4
The current IME activation state and position can be retrieved from the focused gui element.
Finised text output by the IME is converted to a `EET_STRING_INPUT_EVENT`.

**Comment by snowyu** [comment]
@sfan5  thanks so much.

@rubenwardy It doesn't matter. The Win32 IME mechanism should be the same. Some guys really want this feature because they are used to using Windows. BTW, Recently I found an independent UI library, which is very interesting. It is designed for embedded devices, so it is very small and efficient enough:

**Widgets, Styles, Layouts and more**
  - 30+ built-in [Widgets](https://docs.lvgl.io/master/widgets/index.html):  Button, Label, Slider, Chart, Keyboard, Meter, Arc, Table and many more.
  - Flexible [Style system](https://docs.lvgl.io/master/overview/style.html) with  ~100 style properties to customize any part of the widgets in any state.
  - [Flexbox](https://docs.lvgl.io/master/layouts/flex.html) and [Grid](https://docs.lvgl.io/master/layouts/grid.html)-like layouts engines to automatically size and position the widgets in a responsive way.
  - Texts are rendered with UTF-8 encoding supporting CJK, Thai, Hindi, Arabic, Persian writing systems.
  - Word wrapping, kerning, text scrolling, sub-pixel rendering, Pinyin-IME Chinese input, Emojis in texts.
  - Rendering engine supporting animations, anti-aliasing, opacity, smooth scrolling, shadows, image transformation, etc  
  - Supports Mouse, Touchpad, Keypad, Keyboard, External buttons, Encoder [Input devices](https://docs.lvgl.io/master/porting/indev.html).
  - [Multiple display](https://docs.lvgl.io/master/overview/display.html) support.

**Comment by rubenwardy** [comment]
> The Win32 IME mechanism should be the same. Some guys really want this feature because they are used to using Windows

All input would be done using SDL, even on Windows

**Comment by sfan5** [comment]
Sorry for not replying sooner but I will be closing this in favor of our new SDL2 backend which we will be using exclusively soon, so it doesn't make sense to work on features for the legacy backends anymore.

**Pull request closed without merging**
