### PR TITLE
Require C++11 standard to fix issue on OSX builds

### PR DESCRIPTION
**Pull request by JosiahWI**

### CODE REVIEW

**Comment by JosiahWI** [comment]
This was not supposed to pass the checks, according to @hecktest. I have an uneasy feeling that I've overlooked something.

**Comment by sfan5** [comment]
You overlooked that we already do this https://github.com/minetest/irrlicht/blob/4ba0f8d1009275899dd9d244f92527274e93e65b/source/Irrlicht/CMakeLists.txt#L13-L14

**Comment by JosiahWI** [comment]
Well, that's quite the oversight. Does this mean the OSX issue is fixed? This PR can be closed then.

**Comment by sfan5** [comment]
Yes.

**Pull request closed without merging**
