### PR TITLE
Don't draw tooltips

### PR DESCRIPTION
**Pull request by Desour**
For https://github.com/minetest/minetest/pull/13264.

### CODE REVIEW

**Comment by x2048** [comment]
Why not remove the code altogether if we are not using it?

**Comment by Desour** [comment]
I'd then also have to remove plenty of other stuff, like ToolTip in IGUIElement, or the stuff in the skin. It's likely I'd forget something. And there'd be an API break, which would make merging harder I guess.
Also, maybe someone considers at some point that this style of ToolTips is better (the current implementation in GUIFormSpecMenu is kinda ugly), so I didn't want to remove it yet.

**Comment by sfan5** [comment]
> And there'd be an API break, which would make merging harder I guess.

FYI this doesn't matter at all

**Comment by SmallJoker** [comment]
Whereas the API break is no concern, I think that offloading some code to remove clutter from GUIFormSpecMenu would make sense. If there is a reasonable way to integrate Minetest's custom tooltip code into the generic Irrlicht tooltips it could help to make the code cleaner.

**Pull request closed without merging**
