### PR TITLE
Upgrade actions in CI

### PR DESCRIPTION
**Pull request by wsor4035**
Add compact, short information about your PR for easier understanding:

- upgrades all the actions use in workflows to resolve warnings
- created per @sfan5 request in https://github.com/minetest/minetest/pull/14377#issuecomment-1949941967

## To do

This PR is a Work in Progress

- [x] verify no warnings when actions finish

## Outside the scope of just upgrading actions

lukka/run-vcpkg@v7 - https://github.com/minetest/minetest/pull/14377#discussion_r1493006875

## How to test

use your eyes to check actions reports

### CODE REVIEW

**Comment by wsor4035** [comment]
two failing appear to be unrelated to changes made in this pr

**Comment by sfan5** [comment]
Not unrelated but this bug was previously hidden.
You can change the msvc workflows to only upload the sdl artifacts for example.

**Comment by wsor4035** [comment]
> Not unrelated but this bug was previously hidden. You can change the msvc workflows to only upload the sdl artifacts for example.

could this also be solved by changing https://github.com/minetest/irrlicht/blob/master/.github/workflows/build.yml#L261 to be `msvc-${{ matrix.config.arch }}-${{matrix.sdl.use}}` potentially? thoughts?

**Comment by sfan5** [comment]
Yes. Either works.

**Comment by wsor4035** [comment]
in theory fixed (see when tests finish in ... )

**Review by appgurueu — APPROVED** [review]

**Pull request merged**
